### ISSUE TITLE
The right way of how to put the data

### ISSUE THREAD

**Issue by SHAUNZXY** [mcbuehler/DeepSEE#10]
Hi,

I want to use the original dataset for training, could you please tell me how to put the data I downloaded in the right way?  

Best,
Shaun

**Comment by SHAUNZXY** [comment]
What does the dataset folder should be looked like? Are there any rules for the code? Thank you!

**Comment by mcbuehler** [comment]
Please follow the instructions in the [README](https://github.com/mcbuehler/DeepSEE#dataset-preparation). For the original datasets, you can use the implemented dataset classes, e.g., `data/celebamaskhq_dataset.py`.
