### ISSUE TITLE
custom dataset

### ISSUE THREAD

**Issue by monk1108** [mcbuehler/DeepSEE#11]
Hi! DeepSEE is indeed a fantastic work for superresolution, and I'm trying to apply my own dataset to the network. However, I found that for training parameters 'dataset' and 'dataset_mode', there are only choices like celeba and celebamaskhq. How can I modify these parameters to make them suit my own dataset? Thanks!

**Comment by mcbuehler** [comment]
Hi @monk1108 , 
Thank you for your kind words.
You can write your own dataset class, e.g., by adapting the [CelebA dataset](https://github.com/mcbuehler/DeepSEE/blob/master/data/celeba_dataset.py) and adding your custom dataset to the [choices](https://github.com/mcbuehler/DeepSEE/blob/087ca31041f2f55c36cb5a6dc0b5287f84ebf24c/options/base_options.py#L27).
