### ISSUE TITLE
how can I get predicted_labels(.png mask files?)

### ISSUE THREAD

**Issue by opptimus** [mcbuehler/DeepSEE#8]
If I have a new face photo and a already trained model(.pth files), how can I get the predicted_labels(.png mask files)?
Can I use your program to automatically generate it?
Thanks very much!

**Comment by mcbuehler** [comment]
We provide download links for the predicted CelebA and CelebAMask-HQ semantic masks. Please have a look at the section `Dataset Preparation`.

If you want to predict the masks on your own dataset, you can use a [DeepLab V3+](https://github.com/jfzhang95/pytorch-deeplab-xception). Please drop me an email (you can find it on our [paper](https://openaccess.thecvf.com/content/ACCV2020/papers/Buhler_DeepSEE_Deep_Disentangled_Semantic_Explorative_Extreme_Super-Resolution_ACCV_2020_paper.pdf)) and I will make our checkpoints available to you.
